### ISSUE TITLE
Would you help me?

### ISSUE THREAD

**Issue by Cancro29** [Hex2424/esp32_deauth_patch#2]
Hello, I'm the developer of NETHERCAP project that focuses on social engineering and Wi-Fi tools using ESP8266 and ESP-32. I like the fact that you can reverse engineer libnet80211.a, I believe you can do the same to a function called esp_wifi_set_channel() that handles Wi-Fi channel. This function does not work if a station is connected to SoftAP due to limitations from Espressif itself.

Based on this line:

        Serial.println(result);
        Serial.println(esp_err_to_name(result));

the output will be:

-1
ESP_FAIL

I really hope we can work together to bypass this limitation. If you wish to do this for a fee, you can discuss this further via email at nethercap.dev@gmail.com

**Comment by Hex2424** [comment]
Hello, I viewed your repo and it looks very interesting project, yes I may be able to do same thing with other ESP32 limitations such as SoftAP channel changing as soon as it is hardware supported, just need analyze some xtensa assembler registers,

**Comment by Cancro29** [comment]
Thank you. I'll be waiting for further update.

**Comment by Hex2424** [comment]
I wrote you on your email, check it out
